// Generated by CoffeeScript 1.3.3
(function() {
  var assert, zombie;

  assert = require('assert');

  zombie = require('zombie');

  describe('Web', function() {
    return describe('/', function() {
      var $, browser, host, window;
      host = 'http://localhost:5000';
      browser = null;
      window = null;
      $ = null;
      before(function(done) {
        return zombie.visit(host, function(e, br, status) {
          browser = br;
          window = browser.window;
          $ = window.$;
          window.onload();
          return done();
        });
      });
      return it('title is Google', function(done) {
        return assert.equal($('title').text, 'Google');
      });
    });
  });

}).call(this);
