// Generated by CoffeeScript 1.3.3
(function() {
  var browser, should;

  browser = require('tobi').createBrowser(80, 'jangbattle.herokuapp.com');

  should = require('should');

  describe('web', function() {
    return describe('/socket', function() {
      it('titleがJANG Battle!! であること', function(done) {
        return browser.get('/socket', function(res, $) {
          res.should.have.status(200);
          res.should.have.header('Content-Type', 'text/html; charset=utf-8');
          $('title').text().should.equal('JANG Battle!!');
          return done();
        });
      });
      it('ul logが存在すること', function(done) {
        return browser.get('/socket', function(res, $) {
          res.should.have.status(200);
          should.exist($('#log'));
          return $('#log').find('li').size().should.equal(0);
        });
      });
      return it('1回ポストするとul logが子を持つこと', function(done) {
        this.timeout(6000);
        return browser.get('/socket', function(res, $) {
          res.should.have.status(200);
          return browser.click('#input_p', function(res, $) {
            res.should.have.status(200);
            return setTimeout((function() {
              $('#log').find('li').size().should.equal(1);
              return done();
            }), 3000);
          });
        });
      });
    });
  });

}).call(this);
